# Generated by Django 4.1.6 on 2023-02-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6)),
                ('image', models.ImageField(upload_to='prof_pic/')),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
